CREATE TABLE IF NOT EXISTS hit
(
    hit_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app             VARCHAR(64)  NOT NULL,
    uri             VARCHAR(255) NOT NULL,
    ip              VARCHAR(15)  NOT NULL,
    timestamp       TIMESTAMP    NOT NULL,
    );